### ISSUE TITLE
Asuryani Ranger - Wargear Missing

### ISSUE THREAD

**Issue by adotor** [DaeronAlagos/battlescribe-stylesheets#22]
The datacard of the Asuryani Ranger does not contain the Wargear "Cameleoline Cloak".

![missing-cloak](https://user-images.githubusercontent.com/7715059/84564957-07f53000-ad66-11ea-91b3-39ebaa0743e0.png)

Other wargear as the Astartes Intercessor Auspex or Auxiliary Grenade Launcher is rendered, though.

**Comment by DaeronAlagos** [comment]
@adotor Can you attach your .ros file please. Then I will check the data structure and look for differences between the Astartes file we worked with before and the Asuryani one. Thanks

**Comment by adotor** [comment]
Sure. Here it is.


[Sample Asuryani.zip](https://github.com/DaeronAlagos/battlescribe-stylesheets/files/4780667/Sample.Asuryani.zip)

>
            <profile id="c3b4-cd58-0c0a-3584::2891-8ce5-45b9-95cd::08ff-da0f-de4b-d1b7" name="Battle Focus" hidden="false" typeId="1015-f0b1-9137-0060" typeName="Ability">
              <characteristics>
                <characteristic name="Description" typeId="b373-019d-503a-1124">If this model moves or Advances in its Movement phase, weapons (excluding Heavy weapons) are used as if the model had remained stationary.</characteristic>
              </characteristics>
            </profile>
            <profile id="c3b4-cd58-0c0a-3584::ff0a-a701-a86a-3993::7f28-44d7-55b3-e7ef" name="Ancient Doom" hidden="false" typeId="1015-f0b1-9137-0060" typeName="Ability">
              <characteristics>
                <characteristic name="Description" typeId="b373-019d-503a-1124">You can re-roll failed hit rolls in the Fight phase for this model in a battle round in which it charges or is charged by a SLAANESH model. However, you must add 1 to Nerve tests for this model if it is within 3&quot; of any SLAANESH models.</characteristic>
              </characteristics>
            </profile>
            <profile id="c3b4-cd58-0c0a-3584::84d8-5402-d2bb-df5b::d6fb-aea7-412d-ad89" name="Cameleoline Cloak" hidden="false" typeId="0883-432d-b2ca-f11a" typeName="Wargear">
              <characteristics>
                <characteristic name="Ability" typeId="8b56-49a8-40e5-242a">When an enemy player makes a hit roll for a shooting attack that targets this model, and this model is obscured, that hit roll suffers an additional -1 modifier.</characteristic>
              </characteristics>
            </profile>
          </profiles>

[Sample Marines.zip](https://github.com/DaeronAlagos/battlescribe-stylesheets/files/4780674/Sample.Marines.zip)

*Update:* Looks like this Wargear is no selection but a characteristic instead.

**Comment by DaeronAlagos** [comment]
I see the issue. It's wargear that's not in a weapon selection. Easy fix, I'll put non weapon wargear below the weapons

**Comment by DaeronAlagos** [comment]
@adotor I've just pushed some changes. Can you test the latest dist file please.

**Comment by adotor** [comment]
Looking good. The cloak appears on the card. Thank you very much.
