### ISSUE TITLE
Command Roster only outputs the first fire team

### ISSUE THREAD

**Issue by hagamemnon** [DaeronAlagos/battlescribe-stylesheets#3]
Title. I have a Kill Team Command Roster with a Reiver Fire Team as well as a Scout Fire Team. Only the Reiver fire team is being created. Not sure if this is an issue with the stylesheets or BattleScribe's export function.

**Comment by DaeronAlagos** [comment]
Hi, this looks  to be a similar issue to the one about Necrons reported on Reddit. The Reavers Fire Team is correctly identified as a 'unit' and then the members are 'model'. The Scout Fire Team is incorrectly identified as an 'upgrade'. Please raise this issue on the BSData repository and hopefully the maintainer of the Astartes file will be able to correct it.

**Comment by Mad-Spy** [comment]
Fixed in Kill Team datafiles as of v1.1.0, released this morning.
