### ISSUE TITLE
Pagebreaks in middle of datacards when printed

### ISSUE THREAD

**Issue by r4dian** [DaeronAlagos/battlescribe-stylesheets#4]
Would it be possible to space it out so that when printed on A4 the pagebreaks only come between datacards ?

**Comment by DaeronAlagos** [comment]
Hi @r4dian , please correct me if I've misunderstood. My reasoning of not having a space or page break between the cards was that it means less scissor cuts when cutting out the cards. The only forced page-break is between the first page for the roster and the next page starting with the cards.

What is your use case that requires the page breaks between the cards?

**Comment by r4dian** [comment]
Ah, I see.
In that case the issue is the forced page-break is between the first page for the roster and the next page starting with the cards isn't present.
![Capture](https://user-images.githubusercontent.com/1264174/57868566-22737780-77fb-11e9-8cac-bd5dcf85b82d.PNG)

**Comment by r4dian** [comment]
I updated and it works as you intended now.

**Comment by DaeronAlagos** [comment]
Hi @r4dian 

thanks for the update on this. I've made a few changes since this issue was opened and was unable to reproduce. Glad to hear it's working for you now :+1:

**Comment by OftKilted** [comment]
> I updated and it works as you intended now.

@r4dian Is the version you have with the wounds and experience a modification of the current output? That's pretty darn awesome!
